### ISSUE TITLE
Row index is out of bounds in cat_mult_fw_cpp

### ISSUE THREAD

**Issue by mmervecerit** [emmekeaarts/mHMMbayes#24]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/15267081/202025701-cd66b24c-c57b-4673-93f7-9df3a2af3a4d.png">

Why do you think it is throwing this error? I have 2592000 occasions(which is > 2587491) per subject, without missing data.

**Comment by emmekeaarts** [comment]
I tried to replicate your error by simulating data with many occasions (150000) per subject to check if this might be causing the error, but no luck. Could you please try to simulate data with the function sim_mHMM() that is similar to your own and see if you can replicate the error? I need a reproducible example to find out where the bug comes from and fix it. Many thanks!

**Comment by wiesnerfriedman** [comment]
I had this issue and got it to work by ensuring that my values in the obs matrices were integers.

**Comment by lltupper** [comment]
I had this issue as well. The problem was that some of my observations were coded as 0; it seems like the code requires all observed values to correspond to category labels/indices starting at 1, even though they are stored as numeric.

**Comment by emmekeaarts** [comment]
This is indeed the case: "it seems like the code requires all observed values to correspond to category labels/indices starting at 1. " The current version of the package on CRAN now throws an error for categorical data when categorical observations do not equal integers with values running from 1 to number of categories.
